name: Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - apps/vulnerapp/**

env:
  REPOSITORY: vulnerapp:latest

defaults:
  run:
    working-directory: ./apps/vulnerapp

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: docker/setup-qemu-action@v3

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.amd64 --tag $REPOSITORY

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: |
        docker tag $REPOSITORY epomatti/$REPOSITORY
        docker push epomatti/$REPOSITORY
